"""Point cloud generation for Dynamic3D MuJoCo environments.

Provides two complementary methods, selectable via ``generate_point_cloud``:

``method="camera"`` (default)
    Back-projects RGB-D renders from one or more named cameras into
    world-frame XYZ + colour.  Faithfully reproduces what the cameras see,
    including occlusions and lighting.  Returns a :class:`PointCloud`.

``method="mesh"``
    Samples points directly from every geom's triangle mesh (mesh, box,
    cylinder, sphere, capsule) and transforms them to world coordinates.
    Gives complete surface coverage with no occlusion or camera dependency.
    Returns a :class:`MeshPointCloud`.  Requires the ``trimesh`` package.

Typical usage
-------------
::

    env = kinder.make("kinder/BalanceBeam3D-o3-v0")
    env.reset(seed=0)

    sim = get_sim_from_env(env)

    # Camera-based — coloured, view-dependent
    pc = generate_point_cloud(sim, method="camera")
    # pc.xyz -> (N, 3) float32 world-frame positions
    # pc.rgb -> (N, 3) uint8  colours [0, 255]

    # Mesh-based — full coverage, no occlusion (requires trimesh)
    mpc = generate_point_cloud(sim, method="mesh", num_points_per_geom=500)
    # mpc.xyz        -> (N, 3) float32 world-frame positions
    # mpc.geom_names -> list of geom/mesh name strings

"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Literal, Sequence, Union

import mujoco
import numpy as np
from numpy.typing import NDArray

from kinder.envs.dynamic3d.mujoco_utils import MjSim

# ---------------------------------------------------------------------------
# Public data type
# ---------------------------------------------------------------------------


@dataclass
class PointCloud:
    """Merged, world-frame coloured point cloud from one or more cameras.

    Attributes:
        xyz: (N, 3) float32 array of world-frame XYZ positions.
        rgb: (N, 3) uint8 array of RGB colours in [0, 255].
        camera_indices: (N,) int array mapping each point to its source
            camera index in ``camera_names``.
        camera_names: Ordered list of camera names that contributed points.
    """

    xyz: NDArray[np.float32]
    rgb: NDArray[np.uint8]
    camera_indices: NDArray[np.int32]
    camera_names: list[str] = field(default_factory=list)

    def __len__(self) -> int:
        return int(self.xyz.shape[0])

    def filter_by_camera(self, name: str) -> "PointCloud":
        """Return a new PointCloud with only the points from *name*."""
        if name not in self.camera_names:
            raise ValueError(
                f"Camera '{name}' not in point cloud. "
                f"Available cameras: {self.camera_names}"
            )
        idx = self.camera_names.index(name)
        mask = self.camera_indices == idx
        return PointCloud(
            xyz=self.xyz[mask],
            rgb=self.rgb[mask],
            camera_indices=self.camera_indices[mask],
            camera_names=[name],
        )

    def to_dict(self) -> dict[str, NDArray]:
        """Serialise to a plain dict (e.g. for np.savez)."""
        return {
            "xyz": self.xyz,
            "rgb": self.rgb,
            "camera_indices": self.camera_indices,
        }


@dataclass
class MeshPointCloud:
    """World-frame point cloud sampled directly from scene mesh geometry.

    Generated by ``generate_point_cloud(sim, method="mesh")``.  Unlike a
    camera-based :class:`PointCloud`, every surface is covered regardless
    of camera placement or occlusion, but there is no colour information.

    Attributes:
        xyz: (N, 3) float32 array of world-frame XYZ positions.
        geom_indices: (N,) int32 array mapping each point to its source geom's
            0-based sequential position in ``geom_names`` (not a MuJoCo geom ID).
        geom_names: Ordered list of geom/mesh names that contributed points.
    """

    xyz: NDArray[np.float32]
    geom_indices: NDArray[np.int32]
    geom_names: list[str] = field(default_factory=list)

    def __len__(self) -> int:
        return int(self.xyz.shape[0])

    def filter_by_geom(self, name: str) -> "MeshPointCloud":
        """Return a new MeshPointCloud containing only the points from *name*."""
        if name not in self.geom_names:
            raise ValueError(
                f"Geom '{name}' not in point cloud. "
                f"Available geoms: {self.geom_names}"
            )
        idx = self.geom_names.index(name)
        mask = self.geom_indices == idx
        return MeshPointCloud(
            xyz=self.xyz[mask],
            geom_indices=np.zeros(int(mask.sum()), dtype=np.int32),
            geom_names=[name],
        )

    def to_dict(self) -> dict[str, NDArray]:
        """Serialise to a plain dict (e.g. for np.savez)."""
        return {
            "xyz": self.xyz,
            "geom_indices": self.geom_indices,
            "geom_names": np.array(self.geom_names),
        }


# ---------------------------------------------------------------------------
# Intrinsics / extrinsics helpers
# ---------------------------------------------------------------------------


def get_camera_intrinsics(
    model: mujoco.MjModel,
    cam_id: int,
    width: int,
    height: int,
) -> NDArray[np.float64]:
    """Return the 3×3 intrinsic matrix K for a MuJoCo fixed camera.

    MuJoCo uses a single vertical field-of-view (``cam_fovy``, in degrees)
    and assumes square pixels, so ``fx == fy``.

    Args:
        model: The MuJoCo model.
        cam_id: Zero-based camera index.
        width: Render width in pixels.
        height: Render height in pixels.

    Returns:
        K: 3×3 float64 intrinsics matrix::

            [[fx,  0, cx],
             [ 0, fy, cy],
             [ 0,  0,  1]]
    """
    fovy_deg: float = float(model.cam_fovy[cam_id])
    fovy_rad = math.radians(fovy_deg)
    fy = height / (2.0 * math.tan(fovy_rad / 2.0))
    fx = fy  # MuJoCo cameras have square pixels
    cx = width / 2.0
    cy = height / 2.0
    return np.array([[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]], dtype=np.float64)


def get_camera_extrinsics(
    data: mujoco.MjData,
    cam_id: int,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Return the camera-to-world rotation and translation.

    MuJoCo's ``cam_xmat`` stores the camera frame orientation as a 9-element
    row-major rotation matrix whose *columns* are the camera X, Y, Z axes
    expressed in world coordinates (camera-to-world, same convention as
    ``xmat`` for bodies).  The camera Z axis points *backward* (away from
    the scene).

    Args:
        data: MuJoCo simulation data (after ``mj_forward``).
        cam_id: Zero-based camera index.

    Returns:
        R_c2w: (3, 3) rotation matrix, camera → world.
        t_w: (3,) camera position in world frame.
    """
    R_c2w = data.cam_xmat[cam_id].reshape(3, 3).copy().astype(np.float64)
    t_w = data.cam_xpos[cam_id].copy().astype(np.float64)
    return R_c2w, t_w


def depth_buffer_to_metric(
    depth_raw: NDArray[np.float32],
    model: mujoco.MjModel,
) -> NDArray[np.float64]:
    """Convert a raw MuJoCo depth buffer to metric distances (metres).

    MuJoCo uses the standard OpenGL non-linear depth buffer where the stored
    value ``d ∈ [0, 1]`` relates to metric depth ``z`` via::

        z = znear * zfar / (zfar − d * (zfar − znear))

    where ``znear = vis.map.znear * stat.extent`` and similarly for
    ``zfar``.

    Args:
        depth_raw: (H, W) float32 array of raw depth buffer values in [0, 1].
        model: The MuJoCo model (needed for clipping-plane parameters).

    Returns:
        z_metric: (H, W) float64 array of metric distances along the optical
            axis.  Pixels at or beyond the far plane are mapped to ``inf``.
    """
    extent: float = float(model.stat.extent)
    znear: float = float(model.vis.map.znear) * extent
    zfar: float = float(model.vis.map.zfar) * extent
    d = depth_raw.astype(np.float64)
    denom = zfar - d * (zfar - znear)
    # Guard against divide-by-zero (shouldn't happen within [0,1] range)
    with np.errstate(divide="ignore", invalid="ignore"):
        z = np.where(denom > 0.0, znear * zfar / denom, np.inf)
    return z


# ---------------------------------------------------------------------------
# Per-camera back-projection
# ---------------------------------------------------------------------------


def rgbd_to_point_cloud(
    rgb: NDArray[np.uint8],
    depth_raw: NDArray[np.float32],
    cam_id: int,
    model: mujoco.MjModel,
    data: mujoco.MjData,
    *,
    max_depth: float = 10.0,
    min_depth: float = 0.01,
) -> tuple[NDArray[np.float32], NDArray[np.uint8]]:
    """Back-project an RGBD image pair into a world-frame point cloud.

    Pixels whose metric depth falls outside [``min_depth``, ``max_depth``]
    are discarded.

    Args:
        rgb: (H, W, 3) uint8 RGB image.
        depth_raw: (H, W) float32 raw MuJoCo depth buffer (values in [0, 1]).
            The image must already be flipped vertically (as returned by
            ``MjSim.render``).
        cam_id: Zero-based camera index in the model.
        model: MuJoCo model (for intrinsics and depth conversion).
        data: MuJoCo data (for extrinsics).
        max_depth: Discard points farther than this distance (metres).
        min_depth: Discard points closer than this distance (metres).

    Returns:
        xyz_world: (N, 3) float32 positions in world frame.
        rgb_points: (N, 3) uint8 colours.
    """
    height, width = depth_raw.shape
    K = get_camera_intrinsics(model, cam_id, width, height)
    R_c2w, t_w = get_camera_extrinsics(data, cam_id)

    z_metric = depth_buffer_to_metric(depth_raw, model)  # (H, W)

    # Build pixel grid
    u = np.arange(width, dtype=np.float64)  # (W,)
    v = np.arange(height, dtype=np.float64)  # (H,)
    uu, vv = np.meshgrid(u, v)  # (H, W) each

    # Valid mask
    mask = (z_metric >= min_depth) & (z_metric <= max_depth) & np.isfinite(z_metric)
    if not np.any(mask):
        empty = np.empty((0, 3), dtype=np.float32)
        return empty, np.empty((0, 3), dtype=np.uint8)

    z = z_metric[mask]  # (N,)
    u_m = uu[mask]  # (N,)
    v_m = vv[mask]  # (N,)

    # Back-project to camera frame.
    # MuJoCo camera convention: X = right, Y = up, Z = backward.
    # The optical axis points in the -Z direction.
    fx, fy, cx, cy = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
    x_cam = (u_m - cx) / fx * z
    y_cam = -(v_m - cy) / fy * z  # flip: image v increases down, camera Y up
    z_cam = -z  # camera looks in -Z

    pts_cam = np.stack([x_cam, y_cam, z_cam], axis=-1)  # (N, 3)

    # Transform to world frame: p_w = R_c2w @ p_c + t_w
    xyz_world = (pts_cam @ R_c2w.T + t_w).astype(np.float32)

    rgb_points = rgb[mask].astype(np.uint8)
    return xyz_world, rgb_points


# ---------------------------------------------------------------------------
# MjSim-level API
# ---------------------------------------------------------------------------


def generate_scene_point_cloud(
    sim: MjSim,
    camera_names: Sequence[str] | None = None,
    *,
    width: int = 640,
    height: int = 480,
    max_depth: float = 10.0,
    min_depth: float = 0.01,
) -> PointCloud:
    """Generate a merged world-frame point cloud from one or more cameras.

    Renders each requested camera's RGB + depth image, back-projects the
    valid pixels into world-frame 3-D positions, and concatenates the
    results into a single :class:`PointCloud`.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset and
            forwarded).
        camera_names: Camera names to use.  Pass ``None`` to use every
            named camera in the model.
        width: Render width in pixels.
        height: Render height in pixels.
        max_depth: Maximum metric depth to keep (metres).
        min_depth: Minimum metric depth to keep (metres).

    Returns:
        A :class:`PointCloud` containing the merged scene geometry.

    Raises:
        ValueError: If a requested camera name is not found in the model.
    """
    mj_model: mujoco.MjModel = sim.model.mj_model
    mj_data: mujoco.MjData = sim.data.mj_data

    # Resolve camera names → camera IDs
    name2id: dict[str, int] = {}
    for i in range(mj_model.ncam):
        name = mujoco.mj_id2name(  # pylint: disable=no-member
            mj_model, mujoco.mjtObj.mjOBJ_CAMERA, i  # pylint: disable=no-member
        )
        if name is not None:
            name2id[name] = i

    if camera_names is None:
        # Use all named cameras
        cam_items = list(name2id.items())
    else:
        cam_items = []
        for cname in camera_names:
            if cname not in name2id:
                raise ValueError(
                    f"Camera '{cname}' not found in model. "
                    f"Available cameras: {list(name2id.keys())}"
                )
            cam_items.append((cname, name2id[cname]))

    if not cam_items:
        empty_f = np.empty((0, 3), dtype=np.float32)
        empty_u = np.empty((0, 3), dtype=np.uint8)
        empty_i = np.empty((0,), dtype=np.int32)
        return PointCloud(xyz=empty_f, rgb=empty_u, camera_indices=empty_i)

    all_xyz: list[NDArray[np.float32]] = []
    all_rgb: list[NDArray[np.uint8]] = []
    all_idx: list[NDArray[np.int32]] = []
    resolved_names: list[str] = []

    ctx = sim._render_context_offscreen  # pylint: disable=protected-access

    for local_idx, (cname, cam_id) in enumerate(cam_items):
        ctx.render(width=width, height=height, camera_id=cam_id)
        rgb_depth = ctx.read_pixels(width, height, depth=True)
        assert isinstance(rgb_depth, tuple)
        rgb_img, depth_img = rgb_depth
        assert depth_img is not None

        xyz, rgb = rgbd_to_point_cloud(
            rgb_img,
            depth_img,
            cam_id,
            mj_model,
            mj_data,
            max_depth=max_depth,
            min_depth=min_depth,
        )

        if len(xyz) > 0:
            all_xyz.append(xyz)
            all_rgb.append(rgb)
            all_idx.append(np.full(len(xyz), local_idx, dtype=np.int32))
        resolved_names.append(cname)

    if not all_xyz:
        empty_f = np.empty((0, 3), dtype=np.float32)
        empty_u = np.empty((0, 3), dtype=np.uint8)
        empty_i = np.empty((0,), dtype=np.int32)
        return PointCloud(
            xyz=empty_f,
            rgb=empty_u,
            camera_indices=empty_i,
            camera_names=resolved_names,
        )

    return PointCloud(
        xyz=np.concatenate(all_xyz, axis=0),
        rgb=np.concatenate(all_rgb, axis=0),
        camera_indices=np.concatenate(all_idx, axis=0),
        camera_names=resolved_names,
    )


# ---------------------------------------------------------------------------
# Unified dispatcher
# ---------------------------------------------------------------------------


def generate_point_cloud(
    sim: MjSim,
    method: Literal["camera", "mesh"] = "camera",
    *,
    # Camera-based keyword arguments
    camera_names: Sequence[str] | None = None,
    width: int = 640,
    height: int = 480,
    max_depth: float = 10.0,
    min_depth: float = 0.01,
    # Mesh-based keyword argument
    num_points_per_geom: int = 500,
) -> Union[PointCloud, MeshPointCloud]:
    """Generate a world-frame point cloud using either camera or mesh sampling.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset and
            forwarded).
        method: ``"camera"`` (default) back-projects RGB-D renders from named
            cameras into a coloured :class:`PointCloud`.  ``"mesh"`` samples
            points from every geom's triangle mesh and returns a
            :class:`MeshPointCloud` with full surface coverage and no
            occlusion (requires ``trimesh``).
        camera_names: *(camera method only)* Camera names to render.  ``None``
            uses every named camera in the model.
        width: *(camera method only)* Render width in pixels.
        height: *(camera method only)* Render height in pixels.
        max_depth: *(camera method only)* Discard points farther than this
            distance (metres).
        min_depth: *(camera method only)* Discard points closer than this
            distance (metres).
        num_points_per_geom: *(mesh method only)* Number of surface points to
            sample from each geom mesh.

    Returns:
        :class:`PointCloud` when ``method="camera"``;
        :class:`MeshPointCloud` when ``method="mesh"``.

    Raises:
        ValueError: For an unknown *method* string.
        ImportError: When ``method="mesh"`` and ``trimesh`` is not installed.
    """
    if method == "camera":
        return generate_scene_point_cloud(
            sim,
            camera_names=camera_names,
            width=width,
            height=height,
            max_depth=max_depth,
            min_depth=min_depth,
        )
    if method == "mesh":
        return generate_full_point_cloud(sim, num_points_per_geom=num_points_per_geom)
    raise ValueError(f"Unknown method '{method}'. Choose 'camera' or 'mesh'.")


# ---------------------------------------------------------------------------
# Mesh-based point cloud — private geometry helpers
# ---------------------------------------------------------------------------


def _require_trimesh() -> Any:
    try:
        import trimesh  # pylint: disable=import-outside-toplevel

        return trimesh
    except ImportError as exc:
        raise ImportError(
            "The 'trimesh' package is required for mesh-based point cloud "
            "generation. Install it with: pip install trimesh"
        ) from exc


def _transform_from_pos_quat(
    pos: NDArray[np.float64],
    quat: NDArray[np.float64],
) -> NDArray[np.float64]:
    """Build a 4×4 homogeneous transform from a MuJoCo position + quaternion."""
    trimesh = _require_trimesh()
    transform = trimesh.transformations.quaternion_matrix(quat)
    transform[:3, 3] = pos
    return transform


def _make_box_mesh(model: mujoco.MjModel, geom_id: int) -> Any:
    """Create a trimesh box from a MuJoCo mjGEOM_BOX geom (local coords)."""
    trimesh = _require_trimesh()
    half = model.geom_size[geom_id]  # (3,) half-extents
    signs = np.array(
        [
            [-1, -1, -1],
            [-1, -1, 1],
            [-1, 1, -1],
            [-1, 1, 1],
            [1, -1, -1],
            [1, -1, 1],
            [1, 1, -1],
            [1, 1, 1],
        ],
        dtype=np.float64,
    )
    vertices = signs * half
    faces = [
        [0, 1, 3],
        [0, 3, 2],
        [4, 6, 7],
        [4, 7, 5],
        [0, 4, 5],
        [0, 5, 1],
        [2, 3, 7],
        [2, 7, 6],
        [0, 2, 6],
        [0, 6, 4],
        [1, 5, 7],
        [1, 7, 3],
    ]
    return trimesh.Trimesh(vertices=vertices, faces=faces)


def _make_cylinder_mesh(
    model: mujoco.MjModel, geom_id: int, n_segments: int = 20
) -> Any:
    """Create a trimesh cylinder from a MuJoCo mjGEOM_CYLINDER geom."""
    trimesh = _require_trimesh()
    radius, half_height = model.geom_size[geom_id][:2]
    angles = np.linspace(0, 2 * np.pi, n_segments, endpoint=False)
    x, y = radius * np.cos(angles), radius * np.sin(angles)
    bottom = np.stack([x, y, np.full_like(x, -half_height)], axis=1)
    top = np.stack([x, y, np.full_like(x, half_height)], axis=1)
    i_cb, i_ct = 2 * n_segments, 2 * n_segments + 1
    vertices = np.vstack([bottom, top, [[0, 0, -half_height]], [[0, 0, half_height]]])
    faces = []
    for i in range(n_segments):
        j = (i + 1) % n_segments
        faces += [[i, i + n_segments, j + n_segments], [i, j + n_segments, j]]
        faces += [[i_cb, j, i], [i_ct, i + n_segments, j + n_segments]]
    return trimesh.Trimesh(vertices=vertices, faces=faces)


def _make_sphere_mesh(
    model: mujoco.MjModel, geom_id: int, subdivisions: int = 3
) -> Any:
    """Create a trimesh sphere from a MuJoCo mjGEOM_SPHERE geom."""
    trimesh = _require_trimesh()
    radius = float(model.geom_size[geom_id][0])
    return trimesh.creation.icosphere(subdivisions=subdivisions, radius=radius)


def _make_capsule_mesh(model: mujoco.MjModel, geom_id: int) -> Any:
    """Create a trimesh capsule from a MuJoCo mjGEOM_CAPSULE geom."""
    trimesh = _require_trimesh()
    radius, half_height = model.geom_size[geom_id][:2]
    return trimesh.creation.capsule(radius=radius, height=2 * half_height)


# ---------------------------------------------------------------------------
# Mesh-based point cloud — public API
# ---------------------------------------------------------------------------

_MESH_GEOM_TYPES = frozenset(
    [
        mujoco.mjtGeom.mjGEOM_MESH,  # pylint: disable=no-member
        mujoco.mjtGeom.mjGEOM_BOX,  # pylint: disable=no-member
        mujoco.mjtGeom.mjGEOM_CYLINDER,  # pylint: disable=no-member
        mujoco.mjtGeom.mjGEOM_SPHERE,  # pylint: disable=no-member
        mujoco.mjtGeom.mjGEOM_CAPSULE,  # pylint: disable=no-member
    ]
)


def _get_scene_geoms(sim: MjSim) -> list[tuple[int, str, Any]]:
    """Return (geom_id, name, mesh) for every supported geom in the scene."""
    _require_trimesh()
    model = sim.model.mj_model
    result: list[tuple[int, str, Any]] = []

    for geom_id in range(model.ngeom):
        gtype = model.geom_type[geom_id]
        if gtype not in _MESH_GEOM_TYPES:
            continue

        if gtype == mujoco.mjtGeom.mjGEOM_MESH:  # pylint: disable=no-member
            mesh_id = model.geom_dataid[geom_id]
            if mesh_id < 0:
                continue
            raw_name = mujoco.mj_id2name(  # pylint: disable=no-member
                model,
                int(mujoco.mjtObj.mjOBJ_MESH),  # pylint: disable=no-member
                mesh_id,
            )
            name = (raw_name or f"mesh{mesh_id}") + f"_geom{geom_id}"
            trimesh = _require_trimesh()
            mesh = trimesh.Trimesh(
                vertices=model.mesh_vert[
                    model.mesh_vertadr[mesh_id] : model.mesh_vertadr[mesh_id]
                    + model.mesh_vertnum[mesh_id]
                ],
                faces=model.mesh_face[
                    model.mesh_faceadr[mesh_id] : model.mesh_faceadr[mesh_id]
                    + model.mesh_facenum[mesh_id]
                ],
            )
        else:
            raw_name = mujoco.mj_id2name(  # pylint: disable=no-member
                model,
                int(mujoco.mjtObj.mjOBJ_GEOM),  # pylint: disable=no-member
                geom_id,
            )
            name = (raw_name or f"geom{geom_id}") + f"_geom{geom_id}"
            if gtype == mujoco.mjtGeom.mjGEOM_BOX:  # pylint: disable=no-member
                mesh = _make_box_mesh(model, geom_id)
            elif gtype == mujoco.mjtGeom.mjGEOM_CYLINDER:  # pylint: disable=no-member
                mesh = _make_cylinder_mesh(model, geom_id)
            elif gtype == mujoco.mjtGeom.mjGEOM_SPHERE:  # pylint: disable=no-member
                mesh = _make_sphere_mesh(model, geom_id)
            else:  # CAPSULE
                mesh = _make_capsule_mesh(model, geom_id)

        result.append((geom_id, name, mesh))

    return result


def get_scene_meshes(sim: MjSim) -> dict[str, Any]:
    """Return untransformed (local-frame) trimesh objects for every geom.

    Supports ``mjGEOM_MESH``, ``mjGEOM_BOX``, ``mjGEOM_CYLINDER``,
    ``mjGEOM_SPHERE``, and ``mjGEOM_CAPSULE`` geom types.  Geom names are
    suffixed with ``_geomN`` (N = geom index) so that left/right gripper
    fingers sharing a mesh name remain distinct.

    Requires the ``trimesh`` package.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset).

    Returns:
        Mapping from ``"<mesh_or_geom_name>_geomN"`` to an untransformed
        :class:`trimesh.Trimesh` in the geom's local coordinate frame.
    """
    return {name: mesh for _, name, mesh in _get_scene_geoms(sim)}


def generate_full_point_cloud(
    sim: MjSim,
    *,
    num_points_per_geom: int = 500,
) -> MeshPointCloud:
    """Generate a world-frame point cloud by sampling from scene mesh geometry.

    Builds a trimesh for every supported geom (mesh, box, cylinder, sphere,
    capsule), samples ``num_points_per_geom`` surface points from each, then
    transforms them into world coordinates using the current simulation state.

    Unlike camera-based point clouds, every surface is covered regardless of
    camera placement or occlusion.

    Requires the ``trimesh`` package.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset and
            forwarded).
        num_points_per_geom: Number of surface points to sample from each
            geom mesh.

    Returns:
        A :class:`MeshPointCloud` with world-frame XYZ positions.
    """
    model = sim.model.mj_model
    data = sim.data.mj_data

    scene_geoms = _get_scene_geoms(sim)

    all_xyz: list[NDArray[np.float32]] = []
    all_idx: list[NDArray[np.int32]] = []
    geom_names: list[str] = []

    for local_idx, (geom_id, name, mesh) in enumerate(scene_geoms):
        body_id = int(model.geom_bodyid[geom_id])
        body_pos = data.xpos[body_id]
        body_mat = data.xmat[body_id].reshape(3, 3)
        body_transform = np.eye(4)
        body_transform[:3, :3] = body_mat
        body_transform[:3, 3] = body_pos

        local_transform = _transform_from_pos_quat(
            model.geom_pos[geom_id], model.geom_quat[geom_id]
        )
        world_transform = body_transform @ local_transform

        pts = mesh.sample(num_points_per_geom)  # (M, 3)
        pts_h = np.hstack([pts, np.ones((len(pts), 1))])
        xyz = (pts_h @ world_transform.T)[:, :3].astype(np.float32)

        all_xyz.append(xyz)
        all_idx.append(np.full(len(xyz), local_idx, dtype=np.int32))
        geom_names.append(name)

    if not all_xyz:
        return MeshPointCloud(
            xyz=np.empty((0, 3), dtype=np.float32),
            geom_indices=np.empty((0,), dtype=np.int32),
            geom_names=[],
        )

    return MeshPointCloud(
        xyz=np.concatenate(all_xyz, axis=0),
        geom_indices=np.concatenate(all_idx, axis=0),
        geom_names=geom_names,
    )


def generate_track_point_cloud(
    sim: MjSim,
    local_points_dict: dict[str, tuple[int, NDArray[np.float32]]] | None,
    *,
    num_points_per_geom: int = 500,
) -> tuple[MeshPointCloud, dict[str, tuple[int, NDArray[np.float32]]]]:
    """Generate a tracked world-frame point cloud with fixed point identity.

    On the first call (``local_points_dict=None``) samples surface points from
    every geom in local coordinates and stores them.  On every subsequent call
    the *same* local points are re-transformed to their current world positions,
    so point index ``i`` always refers to the same surface location across
    timesteps.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset and forwarded).
        local_points_dict: ``None`` on the first call; the dict returned by a
            previous call on subsequent calls.  Maps geom name to
            ``(geom_id, local_pts)`` — geom_id is the MuJoCo geom index.
        num_points_per_geom: Number of surface points to sample from each geom
            mesh (only used on the first call).

    Returns:
        ``(MeshPointCloud, local_points_dict)`` — pass ``local_points_dict``
        back on the next call to maintain correspondence.
    """
    _require_trimesh()
    model = sim.model.mj_model
    data = sim.data.mj_data

    if local_points_dict is None:
        local_points_dict = {
            name: (geom_id, mesh.sample(num_points_per_geom).astype(np.float32))
            for geom_id, name, mesh in _get_scene_geoms(sim)
        }

    all_xyz: list[NDArray[np.float32]] = []
    all_idx: list[NDArray[np.int32]] = []
    geom_names: list[str] = []

    for local_idx, (name, (geom_id, local_pts)) in enumerate(local_points_dict.items()):
        body_id = int(model.geom_bodyid[geom_id])
        body_transform = np.eye(4)
        body_transform[:3, :3] = data.xmat[body_id].reshape(3, 3)
        body_transform[:3, 3] = data.xpos[body_id]

        world_transform = body_transform @ _transform_from_pos_quat(
            model.geom_pos[geom_id], model.geom_quat[geom_id]
        )

        pts_h = np.hstack([local_pts, np.ones((len(local_pts), 1))])
        xyz = (pts_h @ world_transform.T)[:, :3].astype(np.float32)

        all_xyz.append(xyz)
        all_idx.append(np.full(len(xyz), local_idx, dtype=np.int32))
        geom_names.append(name)

    if not all_xyz:
        return (
            MeshPointCloud(
                xyz=np.empty((0, 3), dtype=np.float32),
                geom_indices=np.empty((0,), dtype=np.int32),
                geom_names=[],
            ),
            local_points_dict,
        )

    return (
        MeshPointCloud(
            xyz=np.concatenate(all_xyz, axis=0),
            geom_indices=np.concatenate(all_idx, axis=0),
            geom_names=geom_names,
        ),
        local_points_dict,
    )


# ---------------------------------------------------------------------------
# Canonical point cloud + EE pose helpers
# ---------------------------------------------------------------------------

_EE_SITE_CANDIDATES: tuple[str, ...] = (
    "robot_pinch_site",
    "eef_site",
    "ee_site",
    "gripper_site",
    "tcp",
    "tool_frame",
    "end_effector_link",
)

_EE_BODY_CANDIDATES: tuple[str, ...] = (
    "EE_BODY_R",
    "end_effector",
    "eef_link",
    "ee_link",
)


def find_ee_frame(
    sim: MjSim,
    frame_name: str | None = None,
) -> tuple[str, Literal["site", "body"]]:
    """Locate the EE frame in the model, supporting both sites and bodies.

    When *frame_name* is given, tries it first as a site then as a body.
    When *frame_name* is ``None``, tries each name in
    :data:`_EE_SITE_CANDIDATES` as sites, then each name in
    :data:`_EE_BODY_CANDIDATES` as bodies.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset).
        frame_name: Explicit site or body name.  ``None`` triggers auto-detect.

    Returns:
        ``(name, frame_type)`` where *frame_type* is ``"site"`` or ``"body"``.

    Raises:
        RuntimeError: If no candidate is found in the model.
    """
    model = sim.model.mj_model

    def _has_site(name: str) -> bool:
        return (
            mujoco.mj_name2id(  # pylint: disable=no-member
                model, mujoco.mjtObj.mjOBJ_SITE, name  # pylint: disable=no-member
            )
            >= 0
        )

    def _has_body(name: str) -> bool:
        return (
            mujoco.mj_name2id(  # pylint: disable=no-member
                model, mujoco.mjtObj.mjOBJ_BODY, name  # pylint: disable=no-member
            )
            >= 0
        )

    if frame_name is not None:
        if _has_site(frame_name):
            return frame_name, "site"
        if _has_body(frame_name):
            return frame_name, "body"
        raise RuntimeError(
            f"EE frame '{frame_name}' not found as site or body. "
            "Pass --ee-site with the correct name."
        )

    for name in _EE_SITE_CANDIDATES:
        if _has_site(name):
            return name, "site"
    for name in _EE_BODY_CANDIDATES:
        if _has_body(name):
            return name, "body"

    raise RuntimeError(
        "No EE frame found in model. "
        f"Tried sites: {', '.join(_EE_SITE_CANDIDATES)}. "
        f"Tried bodies: {', '.join(_EE_BODY_CANDIDATES)}. "
        "Pass --ee-site with the correct site or body name."
    )


def get_ee_pose(
    sim: MjSim,
    frame_name: str,
    frame_type: Literal["site", "body"] = "site",
) -> NDArray[np.float32]:
    """Return the 4×4 world pose of the EE frame as float32.

    The returned matrix is:
    ::

        [[R (3×3), p (3×1)],
         [0, 0, 0,       1]]

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already stepped).
        frame_name: Site or body name (see :func:`find_ee_frame`).
        frame_type: ``"site"`` (default) or ``"body"``.

    Returns:
        (4, 4) float32 homogeneous transform.
    """
    model = sim.model.mj_model
    data = sim.data.mj_data
    T = np.eye(4, dtype=np.float32)
    if frame_type == "site":
        site_id = mujoco.mj_name2id(  # pylint: disable=no-member
            model, mujoco.mjtObj.mjOBJ_SITE, frame_name  # pylint: disable=no-member
        )
        T[:3, :3] = data.site_xmat[site_id].reshape(3, 3).astype(np.float32)
        T[:3, 3] = data.site_xpos[site_id].astype(np.float32)
    else:
        body_id = mujoco.mj_name2id(  # pylint: disable=no-member
            model, mujoco.mjtObj.mjOBJ_BODY, frame_name  # pylint: disable=no-member
        )
        T[:3, :3] = data.xmat[body_id].reshape(3, 3).astype(np.float32)
        T[:3, 3] = data.xpos[body_id].astype(np.float32)
    return T


def sample_canonical_points(
    sim: MjSim,
    *,
    num_points_per_geom: int = 500,
) -> dict[str, tuple[int, NDArray[np.float32]]]:
    """Sample fixed local-frame surface points from every geom.

    Points are sampled once (typically right after ``env.reset()``) and kept
    fixed.  Combined with :func:`get_geom_world_transforms` they allow
    world-frame reconstruction at any later timestep without re-sampling.

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already reset).
        num_points_per_geom: Surface points sampled per geom mesh.

    Returns:
        Mapping from geom name to ``(geom_id, local_pts)`` where
        *local_pts* is a (P, 3) float32 array of local-frame surface points.
    """
    _require_trimesh()
    return {
        name: (geom_id, mesh.sample(num_points_per_geom).astype(np.float32))
        for geom_id, name, mesh in _get_scene_geoms(sim)
    }


def get_geom_world_transforms(
    sim: MjSim,
    geom_ids: dict[str, int],
) -> dict[str, NDArray[np.float32]]:
    """Return the current 4×4 world transforms for the requested geoms.

    The transform maps local geom coordinates to world coordinates:
    ``world_pts = (T @ pts_h.T).T[:, :3]``

    Args:
        sim: A ``kinder`` :class:`MjSim` instance (already stepped).
        geom_ids: Mapping from geom name to geom ID, as returned by
            :func:`sample_canonical_points`.

    Returns:
        Mapping from geom name to (4, 4) float32 homogeneous transform.
    """
    model = sim.model.mj_model
    data = sim.data.mj_data
    transforms: dict[str, NDArray[np.float32]] = {}
    for name, geom_id in geom_ids.items():
        body_id = int(model.geom_bodyid[geom_id])
        body_T = np.eye(4, dtype=np.float64)
        body_T[:3, :3] = data.xmat[body_id].reshape(3, 3)
        body_T[:3, 3] = data.xpos[body_id]
        local_T = _transform_from_pos_quat(
            model.geom_pos[geom_id], model.geom_quat[geom_id]
        )
        transforms[name] = (body_T @ local_T).astype(np.float32)
    return transforms


# ---------------------------------------------------------------------------
# Convenience: extract sim from a wrapped kinder env
# ---------------------------------------------------------------------------


def get_sim_from_env(env: Any) -> MjSim:
    """Extract the underlying :class:`MjSim` from a wrapped kinder env.

    Works with the standard ``kinder.make(...)`` wrapper stack::

        kinder_wrapper
          └─ ObjectCentricRobotEnv (_object_centric_env)
               └─ RobotEnv         (_robot_env)   ← Dynamic3D-specific
                    └─ MujocoEnv   (sim)

    Args:
        env: Any gymnasium-wrapped kinder environment.

    Returns:
        The ``MjSim`` instance (guaranteed non-None after a reset).

    Raises:
        RuntimeError: If the environment is not a Dynamic3D kinder env, or if
            the sim has not been initialised (i.e. no reset has been called).
    """
    unwrapped = env.unwrapped

    # Navigate to the ObjectCentricRobotEnv layer.  It may be the unwrapped
    # env itself (e.g. ObjectCentricTidyBot3DEnv used directly) or reachable
    # via _object_centric_env on an outer wrapper.
    if hasattr(unwrapped, "_object_centric_env"):
        oce = unwrapped._object_centric_env  # pylint: disable=protected-access
    else:
        oce = unwrapped

    # _robot_env is the Dynamic3D-specific marker; other kinder env families
    # (dynamic2d, kinematic2d/3d) do not have it.
    robot_env = getattr(oce, "_robot_env", None)  # pylint: disable=protected-access
    if robot_env is None:
        raise RuntimeError(
            "This environment does not have a '_robot_env' — "
            "point cloud generation requires a Dynamic3D MuJoCo environment."
        )

    sim = robot_env.sim
    if sim is None:
        raise RuntimeError(
            "sim is None — call env.reset() before generating a point cloud."
        )
    return sim
