name: CI Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run autoformat
        run: uv run ./run_autoformat.sh

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK, BLAS, and OSMESA
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: |
          uv run pytest . --pylint -m pylint --pylint-rcfile=.pylintrc --ignore=notebooks -p no:cacheprovider

  static-type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Mypy
        run: |
          uv run mypy . --no-incremental

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK, BLAS, and OSMESA
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Pytest
        env:
          MUJOCO_GL: "osmesa"
          PYOPENGL_PLATFORM: ""
        run: |
          uv run pytest --cache-clear tests/

  notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK, BLAS, and OSMESA
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Notebook tests
        env:
          MUJOCO_GL: "osmesa"
          PYOPENGL_PLATFORM: ""
        run: |
          uv run pytest notebooks/ --nbmake --nbmake-timeout=120
